### ISSUE TITLE
Can sets or lists be the key of a map?

### ISSUE THREAD

**Issue by billpg** [tlocke/zish#10]
"the key part of a pair can be any Zish type except a map."

Suggest that some types are set aside as "simple" types and specify that only those may be the key.

**Comment by gwicksted** [comment]
Yes, a classic `value type`.

Here's my vote:

Decorate each type with a "reference" or "complex" or "value" type.

* Can `null`?  **No**, it's a "reference type"
* Can `decimal`, `float`, `integer`, `timestamp`, `boolean`?  **Yes** they area all "value" types.
* Can `string`?  **Yes**.   (up to a maximum - say 8192 characters?)
* Can `bytes`?  **No**.  See NOTE 1.
* Can `list`, `map`, or `set`?  **No** they are "complex" types.

NOTE 1: Well it is a "value" type... but it is opaque to viewers of the plain text data and are generally geared toward large amounts of data so probably not a good idea to allow.  If yes, a similar length restriction could be placed on keys of this type but I don't feel it would be used often enough to warrant the effort to implement.

**Comment by tlocke** [comment]
I admit I was driven by Python here. The Zish `map` type is implemented as a `dict` in Python, and any immutable type can be a key in a `dict`. The Zish `list` type is implemented as a `tuple` in Python, which is immutable, and so it can be a key.

Actually, thinking about it I'm tempted to go the whole hog and say that _any_ value can be a key!

**Comment by tlocke** [comment]
Volte-face, you're right, we should disallow maps and lists as keys in maps. Sets aren't an issue as we've got rid of those. My reasoning is that in lots of languages the map and list types are mutable, and so aren't suitable for keys.

**Comment by gwicksted** [comment]
One more addition before this issue is closed out.

I know Python allows `None` to be a `dict` key; however, it is not often used (and probably not appropriate) to do so.

In .net, a `null` cannot be the key of a `Dictionary` (it throws).  Is it possible `null` could be added to the list of invalid keys in the hopes of better cross-language support?

**Comment by tlocke** [comment]
Good idea, I've changed the spec accordingly. We want Zish to work nicely with all popular languages.
