### ISSUE TITLE
"Duplicate keys" doesn't define collation

### ISSUE THREAD

**Issue by kbsletten** [tlocke/zish#3]
In order to have better compatibility, there needs to be a decision on how duplicate keys are determined, historically things like case insensitivity have not been the same across platforms, but most languages (exception: SQL) are case-sensitive by default. More interesting are things like Unicode code point equivalences:

* `é` can be encoded two ways: [`U+00E9`](http://www.fileformat.info/info/unicode/char/00E9/index.htm) and [`U+0065`](http://www.fileformat.info/info/unicode/char/0065/index.htm)[`U+0301`](http://www.fileformat.info/info/unicode/char/0301/index.htm) are they equivalent or is a map like `{ "\u00E9": true, "\u0065\u0301": false }` allowed?
* The roman numeral one is commonly represented as [`U+0049`](http://www.fileformat.info/info/unicode/char/0049/index.htm), but can also has its own codepoint [`U+2160`](http://www.fileformat.info/info/unicode/char/2160/index.htm). Are these equivalent or is a map like `{ "\u0049 Love Unicode": true, "\u2160 Love Unicode": false }` allowed?

Further reading: https://en.wikipedia.org/wiki/Unicode_equivalence

**Comment by tlocke** [comment]
Hi @kbsletten, thanks for your comment. I've updated the spec to say:

> Duplicate keys aren't allowed (for keys that
> are strings, the test for uniqeness is done without any 
> https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization[normalization]
> of the strings).
> Duplicate keys aren't allowed (for keys that
> are strings, the test for uniqueness is done without any 
> normalization of the strings).

So both of your example would be allowed. Do you think my change to the spec is adequate?

**Comment by kbsletten** [comment]
That should do it! 👍
