### ISSUE TITLE
Formal specification link incorrect

### ISSUE THREAD

**Issue by gwicksted** [tlocke/zish#4]
In the readme, there is a "Formal specification of Zish" that points to `https://github.com/tlocke/zish/blob/master/zish/Zish.g4` which gives a 404.

The correct link appears to be `https://github.com/tlocke/zish/blob/master/Zish.g4` (remove the `zish` subdirectory)

**Comment by tlocke** [comment]
Thanks @gwicksted, this should be fixed now by https://github.com/tlocke/zish/commit/e5a7c37c41b29dfb0eba8a3cd4737562ac7c9253.
